services:
  db:
    image: mysql:8.0.28
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'cgd'
      # # MYSQL_USER: 'root'
      # MYSQL_PASSWORD: 'cgd'
      MYSQL_ROOT_PASSWORD: 'cgd'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      backend:
  app:
    depends_on:
      - db
    build:
      context: docker
    container_name: app
    expose:
      - '8080'
    ports:
      - "8080:8080"
    restart: always
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/cgd?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: cgd
    networks:
      backend:

volumes:
  db:

networks:
  backend: